---
- name: Install the latest version of Apache on CentOS/RHEL
  hosts: ws
  become: yes

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes

- name: Install Apache on Ubuntu
  hosts: db
  become: yes

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: latest

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes


    