---
- name: class playbook
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    
    - name: installing a package
      apt:
        name: nginx
        state: absent
        update_cache: yes
      when: ansible_os_family=="Debian"
      tags:
        - groupx
     
    - name: install apache 
      package:
        name: httpd
        state: absent
      when: ansible_os_family=="RedHat"
    - name: start httpd daemon
      service:
        name: httpd
        state: started
        enabled: yes
    - name: create user beri
      user:
        name: beri
        comment: "success"
        shell: /bin/bash
    - name: create group
      group:
        name: cloudteam
        state: present
    - name: create index file
      file:
        path: /var/www/html/index.html
        state: touch
    - name: create directory
      file:
        path: /tmp/os
        state: directory
    - name: copy content to index
      copy:
        dest: /var/www/html/index.html
        content: "<h1>This is created using ansible</h1>"
      