pipeline {
    agent {
        label 'agent-ansible'
    }
    triggers {
        cron('0 0 1 * *') 
    }
    stages {
        stage('Patching servers') {
            steps {
                dir('/home/ec2-user/ansible-dev/patching') {
                    // Steps inside this block will execute in /home/ec2-user/ansible-dev
                    sh 'ansible-playbook updates.yml'
                }
            }
        }
    }
}
